### ISSUE TITLE
Automatic File Names

### ISSUE THREAD

**Issue by martin2250** [SeineEloquenz/kit-ilias-opencast-downloader#2]
Hi Alex,

it would be great if the downloaded files would have proper file names and not the random IDs from the server. My proposal would be to use `document.title` as filename and get the extension from the url.

Cheers,
Martin

**Comment by SeineEloquenz** [comment]
Hi Martin,
This sounds like a reasonable improvement.
I'll look into this.

**Comment by SeineEloquenz** [comment]
Implemented in version 1.1

**Comment by martin2250** [comment]
Awesome, thanks!
